CREATE TABLE IF NOT EXISTS denuncias (
	id SERIAL NOT NULL PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	age INTEGER NOT NULL,
	phone VARCHAR(50),
	assedioType VARCHAR(50) NOT NULL,
	description VARCHAR(250) NULL,
	local VARCHAR(50) NOT NULL,
	incontact BOOLEAN NOT NULL DEFAULT FALSE
);
